# Generated by Django 4.0 on 2022-11-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tukbook_usr_uuid', models.TextField(blank=True, max_length=50)),
                ('username', models.TextField(blank=True, max_length=100)),
                ('timestamp_activity', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_users', models.ManyToManyField(blank=True, to='base.Chat_user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_text', models.BooleanField(default=True)),
                ('text', models.TextField(null=True)),
                ('content_file_url', models.URLField(blank=True, max_length=400)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat_room')),
                ('sender_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.chat_user')),
            ],
        ),
    ]
