# Generated by Django 4.0 on 2022-11-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_msg',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='chat_msg',
            name='sender_id',
            field=models.ManyToManyField(blank=True, to='base.Chat_user'),
        ),
    ]
