# Generated by Django 4.1.2 on 2022-11-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_chat_msg_sender_id_chat_msg_sender_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_msg",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
